# Generated by Django 5.0.6 on 2024-11-22 18:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('movie_id', models.IntegerField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('genres', models.CharField(max_length=255)),
                ('mean', models.FloatField(default=0)),
                ('count', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Preference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genre1', models.CharField(blank=True, max_length=255, null=True)),
                ('genre2', models.CharField(blank=True, max_length=255, null=True)),
                ('genre3', models.CharField(blank=True, max_length=255, null=True)),
                ('genre4', models.CharField(blank=True, max_length=255, null=True)),
                ('genre5', models.CharField(blank=True, max_length=255, null=True)),
                ('include_other_genres', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='SimilarMovie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Recommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('movies', models.ManyToManyField(related_name='recommendations', to='recommendations.movie')),
                ('preference', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendation', to='recommendations.preference')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='recommendations', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
