# Generated by Django 5.0.6 on 2024-11-17 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommendations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='preference',
            name='genre1',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='preference',
            name='include_other_genres',
            field=models.BooleanField(default=True),
        ),
    ]
