# Generated by Django 5.0.6 on 2024-11-17 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommendations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='genre',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
