# Generated by Django 5.0.6 on 2024-11-17 03:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recommendations', '0002_movie_genre'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='genre',
            new_name='genres',
        ),
    ]
