# Generated by Django 5.0.6 on 2024-11-17 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommendations', '0004_similarmovie_recommendation_preference'),
    ]

    operations = [
        migrations.AddField(
            model_name='preference',
            name='include_other_genres',
            field=models.BooleanField(default=False),
        ),
    ]
