# Generated by Django 5.0.6 on 2024-12-07 17:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recommendations', '0005_delete_rating'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SimilarMovie',
        ),
    ]
