# Generated by Django 5.0.6 on 2024-11-17 04:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommendations', '0005_preference_include_other_genres'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='preference',
            name='recommendation',
        ),
        migrations.AddField(
            model_name='recommendation',
            name='preference',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='recommendation', to='recommendations.preference'),
            preserve_default=False,
        ),
    ]
